workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile
          flutter pub get
      - name: Build APK
        script: |
          cd mobile
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - mobile/build/app/outputs/flutter-apk/*.apk
